
server:
   port: 9090

spring:
  application:
    name: employe-app


  datasource:
    url: jdbc:mysql://localhost:3306/university
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root


  jpa:
      hibernate:
        ddl-auto=update: update
      properties:
        hibernate:
         # dialect: org.hibernate.dialect.MySQL8InnoDBDialect
